name: Test setup-tarantool action

on:
  push:

jobs:
  test-default-version1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.
      - run: tarantool --version | grep "Tarantool 2.6"
  test-inside-docker-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['debian', 'ubuntu', 'centos:7', 'centos:8']
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - uses: ./.
        with:
          version: 2.4
      - run: tarantool --version | grep "Tarantool 2.4"
