name: Test setup-tarantool action with rocks

on:
  push:

jobs:
  test-with-one-rock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          rocks: luacheck
      - run: tarantool --version | grep "Tarantool 2.6"
  test-with-list-of-rocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          rocks: |
            luacheck
      - run: tarantool --version | grep "Tarantool 2.6"
      - run: luacheck -v | grep "Luacheck:"
  test-with-rocks-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          rocks: |
            luacheck=0.26.0-1
      - run: tarantool --version | grep "Tarantool 2.6"
      - run: luacheck -v | grep "Luacheck"
